### ISSUE TITLE
the height of div container is required?

### ISSUE THREAD

**Issue by cagnot** [gestixi/image-scale#11]
It is great that install this script is easy, and the performance of the scale is perfect. 
My question: I must set the height of the div container, or the image won't be displayed.
Is there a bug or I got some error?
Thanks.

**Comment by nicolasbadia** [comment]
Hi, the point of the library is to scale an image according to its container. If the container has no height it is then normal that nothing is display. If you want the height to be relative to the height of the image, chance is that you don't need this library and simply have to replace the container by the image.
I'm closing this issue. Feel free to reopen and explain your case in more depth if I missed something.
