### ISSUE TITLE
Smooth transition between original size and new calculated size

### ISSUE THREAD

**Issue by 00cpxxx** [gestixi/image-scale#13]
Hi, thanks for the great library. I have a problem when loading portions of a page using ajax and then applying image-scale. The problem is that the images jump from the original size to the new size and that makes it feel uncomfortable when watching things load. Is it possible to have an option to animate the transition from the original size to the new size?

I tried mitigating the issue by tweaking opacity in the whole div but the images load in different times and I don't want to wait for all of them to load before removing alpha.

**Comment by nicolasbadia** [comment]
Hi, did you try the `fadeInDuration` option ?

**Comment by 00cpxxx** [comment]
Sorry for the long delay.

Using fadeInDuration is almost good, the problem is that I can still see the image loading vertically and then it will disappear and fade in. I guess I will combine opacity 0 on every image + fadeInDuration to have what I need.

Since this is a plausible solution you may close this issue as invalid, or you may add an option or extend fadeInDuration to ensure every image starts with opacity 0 so that the fadeIn effect will account for "being loaded images" too.

**Comment by nicolasbadia** [comment]
To have the opacity correctly working without having the image blinking. It must be set before the DOM is ready, using CSS ideally.
What I end up doing is apply the `js-hide` class provided by Modernizr to each image I want to scale, and define the `didScale` delegate to make the images visible once it is scale. This way, if JS is disable, the image stay visible.

If you want, you can even define `didScale` for this globally like this:

```

$.fn.imageScale.defaults.didScale = function() {
    this.$element.css({ visibility: 'visible' });
  };
```
