### ISSUE TITLE
Not working in IE9

### ISSUE THREAD

**Issue by djmtype** [gestixi/image-scale#2]
First, IE9 displays an inline style of `opacity: 0` even after being loaded. The image is not centering or filling the parent. 

All of my scripts are called before the </body> ends.

My code: 

```
jQuery(function($) {
  $(".grid img").imageScale({scale: "best-fill", rescaleOnResize: true, fadeInDuration: "0"});
});
```

Otherwise, IE11, Mac Safari, Chrome, Firefox—all good!

**Comment by nicolasbadia** [comment]
Is IE9 throwing an error ?

**Comment by djmtype** [comment]
No errors, but IE9 isn't displaying the image.  Because of the script,
image is set with an inline style of opacity:0. And no new inline
coordinates are being set on the image like in other browsers.

**Comment by nicolasbadia** [comment]
It looks like IE9 has some issues with the `load` event...

Could you please tell me if this problem is fixe with this patch: https://github.com/gestixi/image-scale/blob/ie9-fix/image-scale.js

**Comment by djmtype** [comment]
Thanks a bunch, that worked. 

Curious… is there a reason why an `opacity` rule is still being declared if `fadeInDuration` is set to `0`? If that's the case, why have it applied at all? 

I can understand if there isn't any fade in duration specified, on initial load the image might appear awkward upon resizing and repositioning. 

However, if I'm including something like [Animate.css](https://daneden.github.io/animate.css/), or just want the opacity set to less than `1` (so titles are more legible above these images), then the fade in duration built into this plugin can work against me rather than help.

Thanks again!

**Comment by nicolasbadia** [comment]
Glad it works.

About the `opacity` rule it was there to prevent an issue where images was blinking just after there resize. But this was just a part of the fix which wasn't preventing the images from blinking... So I just removed that code.

As a record, to prevent images from blinking, I'm adding a specific class to my images which set the `opacity` to 0 (you might want to use modernizr to prevent this class from being active if JS is disabled), and now use the `didScale` callback to set the `opacity` back to 1 once the image is scale.
