### ISSUE TITLE
image-scale fiddles with opacity

### ISSUE THREAD

**Issue by Typetecture** [gestixi/image-scale#3]
Hello, i am using image-scale on images that need to be hidden until i fade them in via jQuery. But it seems like image-scale overwrites the opacity values i set in css.

I dont quite understand why image-scale does it in the first place. Removing the opacity lines in the .js file renders it unusable. Probably because i can't quite write js at all.

Hope you can help.

**Comment by nicolasbadia** [comment]
Hi. 
Did you try the latest version? 
I recently removed the opacity override as explained here: https://github.com/gestixi/image-scale/issues/2
