### ISSUE TITLE
parent option

### ISSUE THREAD

**Issue by BlueSky1021** [gestixi/image-scale#6]
I can't make the parent option work..

**Comment by nicolasbadia** [comment]
The parent option works fine for us.
Could you please provide some code or a [fiddle](https://jsfiddle.net/) ?

**Comment by BlueSky1021** [comment]
This is a demo i created [jsfiddle demo](https://jsfiddle.net/BlueSky1021/fvv3vh1s/4/?utm_source=website&utm_medium=embed&utm_campaign=fvv3vh1s)

This is the script:

```
// Script without the parent option
$(function() {
  $("img.scale").imageScale();
});
// Script with the parent option
$(function() {
  $("img.scale-child").imageScale({
    parent: 'div.image-container-parent'
  });
});
```

I hope i am using it in a right way.

I hope you can help me on my problem.

**Comment by nicolasbadia** [comment]
Thanks for the example.
The problem is that the parent option require a jQuery object.
You should change `parent: 'div.image-container-parent'` by `parent: $('div.image-container-parent')`
